import { PropstackUnit } from "@/lib/propstack/types";

const imageSet = (seed: string) => ({
  original: `https://picsum.photos/seed/${seed}/1920/1280`,
  big: `https://picsum.photos/seed/${seed}-big/1400/933`,
  medium: `https://picsum.photos/seed/${seed}-medium/900/600`,
  thumb: `https://picsum.photos/seed/${seed}-thumb/360/240`,
});

export const mockProperties: PropstackUnit[] = [
  {
    id: "erl-101",
    title: "Stilvolle Altbauwohnung am Burgberg",
    unit_id: "WEID-ERL-101",
    street: "Burgbergstraße",
    house_number: "18",
    zip_code: "91054",
    city: "Erlangen",
    number_of_rooms: 3.5,
    price: 489000,
    base_rent: null,
    living_space: 112,
    plot_area: null,
    number_of_bed_rooms: 2,
    number_of_bath_rooms: 1,
    marketing_type: "BUY",
    rs_type: "APARTMENT",
    rs_category: "MAISONETTE",
    images: [imageSet("weid-erl-101-a"), imageSet("weid-erl-101-b"), imageSet("weid-erl-101-c")],
    status: { id: 1, name: "Verf\u00fcgbar", color: "#8a9a7e" },
    description_note:
      "Diese charmante Maisonette verbindet historische Details mit modernem Wohnkomfort. Hohe Decken, Echtholzparkett und ein offener Wohnbereich schaffen ein ruhiges, hochwertiges Ambiente mit Blick ins Gr\u00fcne.",
    location_note:
      "Am Burgberg wohnen Sie in einer der begehrtesten Lagen Erlangens: kurze Wege in die Altstadt, schnelle Anbindung zur Uni und gleichzeitig ein gewachsenes, ruhiges Wohnumfeld.",
    construction_year: 1912,
  },
  {
    id: "erl-102",
    title: "Familienhaus mit Garten in Sieglitzhof",
    unit_id: "WEID-ERL-102",
    street: "Ludwig-Feuerbach-Stra\u00dfe",
    house_number: "7",
    zip_code: "91054",
    city: "Erlangen",
    number_of_rooms: 6,
    price: 865000,
    base_rent: null,
    living_space: 184,
    plot_area: 512,
    number_of_bed_rooms: 4,
    number_of_bath_rooms: 2,
    marketing_type: "BUY",
    rs_type: "HOUSE",
    rs_category: "DETACHED_HOUSE",
    images: [imageSet("weid-erl-102-a"), imageSet("weid-erl-102-b"), imageSet("weid-erl-102-c")],
    status: { id: 1, name: "Verf\u00fcgbar", color: "#8a9a7e" },
    description_note:
      "Ein durchdachtes Einfamilienhaus mit gro\u00dfz\u00fcgigem Grundriss, sonniger Terrasse und eingewachsenem Garten. Der Wohnbereich \u00f6ffnet sich \u00fcber gro\u00dfe Fensterfl\u00e4chen zum Au\u00dfenraum.",
    location_note:
      "Sieglitzhof bietet eine starke Infrastruktur f\u00fcr Familien: Schulen, Einkauf und Freizeitangebote sind schnell erreichbar. Die Innenstadt liegt nur wenige Minuten entfernt.",
    construction_year: 2006,
  },
  {
    id: "erl-103",
    title: "Neubau-Penthouse mit Dachterrasse",
    unit_id: "WEID-ERL-103",
    street: "N\u00fcrnberger Stra\u00dfe",
    house_number: "121",
    zip_code: "91052",
    city: "Erlangen",
    number_of_rooms: 4,
    price: 1295000,
    base_rent: null,
    living_space: 168,
    plot_area: null,
    number_of_bed_rooms: 3,
    number_of_bath_rooms: 2,
    marketing_type: "BUY",
    rs_type: "APARTMENT",
    rs_category: "PENTHOUSE",
    images: [imageSet("weid-erl-103-a"), imageSet("weid-erl-103-b"), imageSet("weid-erl-103-c")],
    status: { id: 2, name: "Reserviert", color: "#c8b9a5" },
    description_note:
      "Das Penthouse \u00fcberzeugt mit privatem Aufzugzugang, gro\u00dfz\u00fcgiger Dachterrasse und einem offenen Wohn-Essbereich. Hochwertige Materialien unterstreichen den urbanen, eleganten Charakter.",
    location_note:
      "Zentrale Lage mit kurzer Distanz zum Bahnhof Erlangen und direkter Anbindung Richtung N\u00fcrnberg. Caf\u00e9s, Restaurants und Nahversorgung liegen im direkten Umfeld.",
    construction_year: 2022,
  },
  {
    id: "erl-201",
    title: "Lichtdurchflutete 2-Zimmer-Wohnung in Alterlangen",
    unit_id: "WEID-ERL-201",
    street: "Dompfaffstra\u00dfe",
    house_number: "22",
    zip_code: "91056",
    city: "Erlangen",
    number_of_rooms: 2,
    price: 980,
    base_rent: 980,
    living_space: 64,
    plot_area: null,
    number_of_bed_rooms: 1,
    number_of_bath_rooms: 1,
    marketing_type: "RENT",
    rs_type: "APARTMENT",
    rs_category: "APARTMENT",
    images: [imageSet("weid-erl-201-a"), imageSet("weid-erl-201-b"), imageSet("weid-erl-201-c")],
    status: { id: 1, name: "Verf\u00fcgbar", color: "#8a9a7e" },
    description_note:
      "Diese modernisierte Wohnung eignet sich ideal f\u00fcr Singles oder Paare. Der Grundriss ist effizient, die K\u00fcche offen gestaltet und der Balkon nach Westen ausgerichtet.",
    location_note:
      "Alterlangen verbindet ruhiges Wohnen mit schneller Erreichbarkeit der Innenstadt. Bushaltestellen, Nahversorger und gr\u00fcne Wege entlang der Regnitz sind fu\u00dfl\u00e4ufig erreichbar.",
    construction_year: 1998,
  },
  {
    id: "erl-202",
    title: "Gro\u00dfz\u00fcgiges Stadthaus zur Miete in Bruck",
    unit_id: "WEID-ERL-202",
    street: "Bunsenstra\u00dfe",
    house_number: "41",
    zip_code: "91058",
    city: "Erlangen",
    number_of_rooms: 5,
    price: 2450,
    base_rent: 2450,
    living_space: 172,
    plot_area: 280,
    number_of_bed_rooms: 4,
    number_of_bath_rooms: 2,
    marketing_type: "RENT",
    rs_type: "HOUSE",
    rs_category: "TERRACED_HOUSE",
    images: [imageSet("weid-erl-202-a"), imageSet("weid-erl-202-b"), imageSet("weid-erl-202-c")],
    status: { id: 1, name: "Verf\u00fcgbar", color: "#8a9a7e" },
    description_note:
      "Ein modernes Stadthaus mit drei Ebenen, eigenem Gartenanteil und viel Platz f\u00fcr Homeoffice und Familie. Gro\u00dfe Fenster sorgen f\u00fcr helle, freundliche R\u00e4ume.",
    location_note:
      "Bruck bietet eine exzellente Verkehrsanbindung, kurze Wege zu Siemens-Campus und A73 sowie ein lebendiges Quartier mit Schulen, Sport und Gastronomie.",
    construction_year: 2016,
  },
  {
    id: "erl-203",
    title: "M\u00f6blierte Maisonette nahe Siemens Campus",
    unit_id: "WEID-ERL-203",
    street: "Schenkstra\u00dfe",
    house_number: "9",
    zip_code: "91052",
    city: "Erlangen",
    number_of_rooms: 3,
    price: 1690,
    base_rent: 1690,
    living_space: 96,
    plot_area: null,
    number_of_bed_rooms: 2,
    number_of_bath_rooms: 2,
    marketing_type: "RENT",
    rs_type: "APARTMENT",
    rs_category: "MAISONETTE",
    images: [imageSet("weid-erl-203-a"), imageSet("weid-erl-203-b"), imageSet("weid-erl-203-c")],
    status: { id: 2, name: "Reserviert", color: "#c8b9a5" },
    description_note:
      "Die voll ausgestattete Maisonette ist sofort bezugsbereit und kombiniert urbanes Design mit warmen Materialien. Besonders attraktiv ist die Galerieebene mit separatem Arbeitsbereich.",
    location_note:
      "Zwischen Innenstadt und Siemens Campus gelegen profitieren Sie von kurzen Wegen zu Arbeitgebern, Bahnhof und Nahversorgung. Die Lage eignet sich optimal f\u00fcr beruflich mobile Mieter.",
    construction_year: 2019,
  },
];
